# Generated by Django 4.1.3 on 2022-11-13 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preflop',
            name='card2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='poker.card'),
        ),
        migrations.AddField(
            model_name='flop',
            name='card2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='poker.card'),
        ),
        migrations.AddField(
            model_name='flop',
            name='card3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='poker.card'),
        ),
    ]
